export const GET_VIDEOGAME_BY_ID = 'GET_VIDEOGAME_BY_ID';
export const GET_GENRES = 'GET_GENRES';
export const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
export const POST_VIDEOGAME = 'POST_VIDEOGAME';
export const GET_PLATFORMS = 'GET_PLATFORMS';
